
# language: swift
# osx_image: xcode10
# script: swift test

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode10
      language: objective-c
      sudo: required

script:
  - swift build
  - swift test

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

# before_install:
#   - chmod ugo+x ./Scripts/InstallSwift.sh
#   - . ./Scripts/InstallSwift.sh

# notifications:
#   email:
#     on_success: never
#     on_failure: change